---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drill-pvc
  labels:
    app: drill
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drill
  labels:
    app: drill
spec:
  selector:
    matchLabels:
      app: drill
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drill
    spec:
      containers:
      - image: kubeworks/drill:dev
        name: drill
        ports:
        - containerPort: 8047
          name: drill-port
        stdin: true
        volumeMounts:
        - name: drill-pv
          mountPath: /tmp/drill
      volumes:
        - name: drill-pv
          persistentVolumeClaim:
            claimName: drill-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: drill-svc
spec:
 type: NodePort
 selector:
   app: drill
 ports:
   - name: http
     protocol: TCP
     port: 8047
     nodePort: 30847
 selector:
   app: drill
